// <auto-generated/>
// Last modified at 2023-09-24.

namespace HyperSharp.Protocol
{
    /// <summary>
    /// Provides common values for HTTP header names.
    /// </summary>
    /// <remarks>
    /// This enum is NOT exhaustive. It only contains the most common header names.
    /// </remarks>
    public enum HyperHeaderName
    {
        /// <summary>
        /// Represents the <c>Accept</c> header.
        /// </summary>
        Accept,

        /// <summary>
        /// Represents the <c>Accept-Charset</c> header.
        /// </summary>
        AcceptCharset,

        /// <summary>
        /// Represents the <c>Accept-Encoding</c> header.
        /// </summary>
        AcceptEncoding,

        /// <summary>
        /// Represents the <c>Accept-Language</c> header.
        /// </summary>
        AcceptLanguage,

        /// <summary>
        /// Represents the <c>Accept-Ranges</c> header.
        /// </summary>
        AcceptRanges,

        /// <summary>
        /// Represents the <c>Access-Control-Allow-Credentials</c> header.
        /// </summary>
        AccessControlAllowCredentials,

        /// <summary>
        /// Represents the <c>Access-Control-Allow-Headers</c> header.
        /// </summary>
        AccessControlAllowHeaders,

        /// <summary>
        /// Represents the <c>Access-Control-Allow-Methods</c> header.
        /// </summary>
        AccessControlAllowMethods,

        /// <summary>
        /// Represents the <c>Access-Control-Allow-Origin</c> header.
        /// </summary>
        AccessControlAllowOrigin,

        /// <summary>
        /// Represents the <c>Access-Control-Expose-Headers</c> header.
        /// </summary>
        AccessControlExposeHeaders,

        /// <summary>
        /// Represents the <c>Access-Control-Max-Age</c> header.
        /// </summary>
        AccessControlMaxAge,

        /// <summary>
        /// Represents the <c>Access-Control-Request-Headers</c> header.
        /// </summary>
        AccessControlRequestHeaders,

        /// <summary>
        /// Represents the <c>Access-Control-Request-Method</c> header.
        /// </summary>
        AccessControlRequestMethod,

        /// <summary>
        /// Represents the <c>Age</c> header.
        /// </summary>
        Age,

        /// <summary>
        /// Represents the <c>Allow</c> header.
        /// </summary>
        Allow,

        /// <summary>
        /// Represents the <c>:authority</c> header.
        /// </summary>
        Authority,

        /// <summary>
        /// Represents the <c>Authorization</c> header.
        /// </summary>
        Authorization,

        /// <summary>
        /// Represents the <c>Cache-Control</c> header.
        /// </summary>
        CacheControl,

        /// <summary>
        /// Represents the <c>Connection</c> header.
        /// </summary>
        Connection,

        /// <summary>
        /// Represents the <c>Content-Disposition</c> header.
        /// </summary>
        ContentDisposition,

        /// <summary>
        /// Represents the <c>Content-Encoding</c> header.
        /// </summary>
        ContentEncoding,

        /// <summary>
        /// Represents the <c>Content-Language</c> header.
        /// </summary>
        ContentLanguage,

        /// <summary>
        /// Represents the <c>Content-Length</c> header.
        /// </summary>
        ContentLength,

        /// <summary>
        /// Represents the <c>Content-Location</c> header.
        /// </summary>
        ContentLocation,

        /// <summary>
        /// Represents the <c>Content-MD5</c> header.
        /// </summary>
        ContentMD5,

        /// <summary>
        /// Represents the <c>Content-Range</c> header.
        /// </summary>
        ContentRange,

        /// <summary>
        /// Represents the <c>Content-Security-Policy</c> header.
        /// </summary>
        ContentSecurityPolicy,

        /// <summary>
        /// Represents the <c>Content-Security-Policy-Report-Only</c> header.
        /// </summary>
        ContentSecurityPolicyReportOnly,

        /// <summary>
        /// Represents the <c>Content-Type</c> header.
        /// </summary>
        ContentType,

        /// <summary>
        /// Represents the <c>Cookie</c> header.
        /// </summary>
        Cookie,

        /// <summary>
        /// Represents the <c>Date</c> header.
        /// </summary>
        Date,

        /// <summary>
        /// Represents the <c>ETag</c> header.
        /// </summary>
        ETag,

        /// <summary>
        /// Represents the <c>Expires</c> header.
        /// </summary>
        Expires,

        /// <summary>
        /// Represents the <c>Expect</c> header.
        /// </summary>
        Expect,

        /// <summary>
        /// Represents the <c>From</c> header.
        /// </summary>
        From,

        /// <summary>
        /// Represents the <c>Host</c> header.
        /// </summary>
        Host,

        /// <summary>
        /// Represents the <c>If-Match</c> header.
        /// </summary>
        IfMatch,

        /// <summary>
        /// Represents the <c>If-Modified-Since</c> header.
        /// </summary>
        IfModifiedSince,

        /// <summary>
        /// Represents the <c>If-None-Match</c> header.
        /// </summary>
        IfNoneMatch,

        /// <summary>
        /// Represents the <c>If-Range</c> header.
        /// </summary>
        IfRange,

        /// <summary>
        /// Represents the <c>If-Unmodified-Since</c> header.
        /// </summary>
        IfUnmodifiedSince,

        /// <summary>
        /// Represents the <c>Last-Modified</c> header.
        /// </summary>
        LastModified,

        /// <summary>
        /// Represents the <c>Location</c> header.
        /// </summary>
        Location,

        /// <summary>
        /// Represents the <c>Max-Forwards</c> header.
        /// </summary>
        MaxForwards,

        /// <summary>
        /// Represents the <c>:method</c> header.
        /// </summary>
        Method,

        /// <summary>
        /// Represents the <c>Origin</c> header.
        /// </summary>
        Origin,

        /// <summary>
        /// Represents the <c>:path</c> header.
        /// </summary>
        Path,

        /// <summary>
        /// Represents the <c>Pragma</c> header.
        /// </summary>
        Pragma,

        /// <summary>
        /// Represents the <c>Proxy-Authenticate</c> header.
        /// </summary>
        ProxyAuthenticate,

        /// <summary>
        /// Represents the <c>Proxy-Authorization</c> header.
        /// </summary>
        ProxyAuthorization,

        /// <summary>
        /// Represents the <c>Range</c> header.
        /// </summary>
        Range,

        /// <summary>
        /// Represents the <c>Referer</c> header.
        /// </summary>
        Referer,

        /// <summary>
        /// Represents the <c>Retry-After</c> header.
        /// </summary>
        RetryAfter,

        /// <summary>
        /// Represents the <c>:scheme</c> header.
        /// </summary>
        Scheme,

        /// <summary>
        /// Represents the <c>Server</c> header.
        /// </summary>
        Server,

        /// <summary>
        /// Represents the <c>Set-Cookie</c> header.
        /// </summary>
        SetCookie,

        /// <summary>
        /// Represents the <c>:status</c> header.
        /// </summary>
        Status,

        /// <summary>
        /// Represents the <c>Strict-Transport-Security</c> header.
        /// </summary>
        StrictTransportSecurity,

        /// <summary>
        /// Represents the <c>TE</c> header.
        /// </summary>
        TE,

        /// <summary>
        /// Represents the <c>Trailer</c> header.
        /// </summary>
        Trailer,

        /// <summary>
        /// Represents the <c>Transfer-Encoding</c> header.
        /// </summary>
        TransferEncoding,

        /// <summary>
        /// Represents the <c>Upgrade</c> header.
        /// </summary>
        Upgrade,

        /// <summary>
        /// Represents the <c>User-Agent</c> header.
        /// </summary>
        UserAgent,

        /// <summary>
        /// Represents the <c>Vary</c> header.
        /// </summary>
        Vary,

        /// <summary>
        /// Represents the <c>Via</c> header.
        /// </summary>
        Via,

        /// <summary>
        /// Represents the <c>Warning</c> header.
        /// </summary>
        Warning,

        /// <summary>
        /// Represents the <c>Sec-WebSocket-Protocol</c> header.
        /// </summary>
        WebSocketSubProtocols,

        /// <summary>
        /// Represents the <c>WWW-Authenticate</c> header.
        /// </summary>
        WWWAuthenticate
    }
}
