// <auto-generated/>
// Last modified at 2024-06-28.

#nullable enable
namespace HyperSharp.Protocol
{
    public readonly partial record struct HyperStatus
    {
        /// <inheritdoc cref="global::System.Net.HttpStatusCode.MultipleChoices" />
        public static HyperStatus MultipleChoices() => new(global::System.Net.HttpStatusCode.MultipleChoices, new HyperHeaderCollection(), null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.MultipleChoices" />
        /// <param name="body">The body of the response.</param>
        public static HyperStatus MultipleChoices(object? body) => new(global::System.Net.HttpStatusCode.MultipleChoices, new HyperHeaderCollection(), body);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.MultipleChoices" />
        /// <param name="headers">The headers of the response.</param>
        public static HyperStatus MultipleChoices(HyperHeaderCollection headers) => new(global::System.Net.HttpStatusCode.MultipleChoices, headers, null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.MultipleChoices" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus MultipleChoices(HyperHeaderCollection headers, object? body) => new(global::System.Net.HttpStatusCode.MultipleChoices, headers, body);
    }
}
