// <auto-generated/>
// Last modified at 2023-09-24.

#nullable enable
namespace HyperSharp.Protocol
{
    public readonly partial record struct HyperStatus
    {
        #if NET8_0_OR_GREATER

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.NonAuthoritativeInformation" />
        public static HyperStatus NonAuthoritativeInformation() => new(global::System.Net.HttpStatusCode.NonAuthoritativeInformation, new HyperHeaderCollection(), null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.NonAuthoritativeInformation" />
        /// <param name="body">The body of the response.</param>
        public static HyperStatus NonAuthoritativeInformation(object? body) => new(global::System.Net.HttpStatusCode.NonAuthoritativeInformation, new HyperHeaderCollection(), body);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.NonAuthoritativeInformation" />
        /// <param name="headers">The headers of the response.</param>
        public static HyperStatus NonAuthoritativeInformation(HyperHeaderCollection headers) => new(global::System.Net.HttpStatusCode.NonAuthoritativeInformation, headers, null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.NonAuthoritativeInformation" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus NonAuthoritativeInformation(HyperHeaderCollection headers, object? body) => new(global::System.Net.HttpStatusCode.NonAuthoritativeInformation, headers, body);

        #endif
    }
}
