// <auto-generated/>
// Last modified at 2023-09-24.

#nullable enable
namespace HyperSharp.Protocol
{
    public readonly partial record struct HyperStatus
    {
        #if NET8_0_OR_GREATER

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Unused" />
        public static HyperStatus Unused() => new(global::System.Net.HttpStatusCode.Unused, new HyperHeaderCollection(), null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Unused" />
        /// <param name="body">The body of the response.</param>
        public static HyperStatus Unused(object? body) => new(global::System.Net.HttpStatusCode.Unused, new HyperHeaderCollection(), body);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Unused" />
        /// <param name="headers">The headers of the response.</param>
        public static HyperStatus Unused(HyperHeaderCollection headers) => new(global::System.Net.HttpStatusCode.Unused, headers, null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Unused" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus Unused(HyperHeaderCollection headers, object? body) => new(global::System.Net.HttpStatusCode.Unused, headers, body);

        #endif
    }
}
