// <auto-generated/>
// Last modified at 2023-09-24.

#nullable enable
namespace HyperSharp.Protocol
{
    public readonly partial record struct HyperStatus
    {
        #if NET7_0_OR_GREATER

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.AlreadyReported" />
        public static HyperStatus AlreadyReported() => new(global::System.Net.HttpStatusCode.AlreadyReported, new HyperHeaderCollection(), null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.AlreadyReported" />
        /// <param name="body">The body of the response.</param>
        public static HyperStatus AlreadyReported(object? body) => new(global::System.Net.HttpStatusCode.AlreadyReported, new HyperHeaderCollection(), body);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.AlreadyReported" />
        /// <param name="headers">The headers of the response.</param>
        public static HyperStatus AlreadyReported(HyperHeaderCollection headers) => new(global::System.Net.HttpStatusCode.AlreadyReported, headers, null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.AlreadyReported" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus AlreadyReported(HyperHeaderCollection headers, object? body) => new(global::System.Net.HttpStatusCode.AlreadyReported, headers, body);

        #endif
    }
}
