// <auto-generated/>
// Last modified at 2024-07-30.

#nullable enable
namespace HyperSharp.Protocol
{
    public readonly partial record struct HyperStatus
    {
        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Found" />
        public static HyperStatus Found() => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.Found
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Found" />
        /// <param name="body">The body of the response.</param>
        public static HyperStatus Found(object? body) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.Found,
            Body = body
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Found" />
        /// <param name="body">The body of the response.</param>
        /// <param name="serializer">Which serializer to use to serialize the body.</param>
        public static HyperStatus Found(object? body, HyperSerializerDelegate serializer) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.Found,
            Body = body,
            Serializer = serializer
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Found" />
        /// <param name="headers">The headers of the response.</param>
        public static HyperStatus Found(HyperHeaderCollection headers) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.Found,
            Headers = headers
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Found" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus Found(HyperHeaderCollection headers, object? body) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.Found,
            Headers = headers,
            Body = body
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Found" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus Found(HyperHeaderCollection headers, object? body, HyperSerializerDelegate serializer) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.Found,
            Headers = headers,
            Body = body,
            Serializer = serializer
        };
    }
}
