// <auto-generated/>
// Last modified at 2023-09-24.

#nullable enable
namespace HyperSharp.Protocol
{
    public readonly partial record struct HyperStatus
    {
        #if NET7_0_OR_GREATER

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.BadGateway" />
        public static HyperStatus BadGateway() => new(global::System.Net.HttpStatusCode.BadGateway, new HyperHeaderCollection(), null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.BadGateway" />
        /// <param name="body">The body of the response.</param>
        public static HyperStatus BadGateway(object? body) => new(global::System.Net.HttpStatusCode.BadGateway, new HyperHeaderCollection(), body);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.BadGateway" />
        /// <param name="headers">The headers of the response.</param>
        public static HyperStatus BadGateway(HyperHeaderCollection headers) => new(global::System.Net.HttpStatusCode.BadGateway, headers, null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.BadGateway" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus BadGateway(HyperHeaderCollection headers, object? body) => new(global::System.Net.HttpStatusCode.BadGateway, headers, body);

        #endif
    }
}
