// <auto-generated/>
// Last modified at 2023-09-24.

#nullable enable
namespace HyperSharp.Protocol
{
    public readonly partial record struct HyperStatus
    {
        #if NET8_0_OR_GREATER

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Continue" />
        public static HyperStatus Continue() => new(global::System.Net.HttpStatusCode.Continue, new HyperHeaderCollection(), null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Continue" />
        /// <param name="body">The body of the response.</param>
        public static HyperStatus Continue(object? body) => new(global::System.Net.HttpStatusCode.Continue, new HyperHeaderCollection(), body);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Continue" />
        /// <param name="headers">The headers of the response.</param>
        public static HyperStatus Continue(HyperHeaderCollection headers) => new(global::System.Net.HttpStatusCode.Continue, headers, null);

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.Continue" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus Continue(HyperHeaderCollection headers, object? body) => new(global::System.Net.HttpStatusCode.Continue, headers, body);

        #endif
    }
}
