// <auto-generated/>
// Last modified at 2024-07-30.

#nullable enable
namespace HyperSharp.Protocol
{
    public readonly partial record struct HyperStatus
    {
        /// <inheritdoc cref="global::System.Net.HttpStatusCode.HttpVersionNotSupported" />
        public static HyperStatus HttpVersionNotSupported() => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.HttpVersionNotSupported
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.HttpVersionNotSupported" />
        /// <param name="body">The body of the response.</param>
        public static HyperStatus HttpVersionNotSupported(object? body) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.HttpVersionNotSupported,
            Body = body
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.HttpVersionNotSupported" />
        /// <param name="body">The body of the response.</param>
        /// <param name="serializer">Which serializer to use to serialize the body.</param>
        public static HyperStatus HttpVersionNotSupported(object? body, HyperSerializerDelegate serializer) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.HttpVersionNotSupported,
            Body = body,
            Serializer = serializer
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.HttpVersionNotSupported" />
        /// <param name="headers">The headers of the response.</param>
        public static HyperStatus HttpVersionNotSupported(HyperHeaderCollection headers) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.HttpVersionNotSupported,
            Headers = headers
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.HttpVersionNotSupported" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus HttpVersionNotSupported(HyperHeaderCollection headers, object? body) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.HttpVersionNotSupported,
            Headers = headers,
            Body = body
        };

        /// <inheritdoc cref="global::System.Net.HttpStatusCode.HttpVersionNotSupported" />
        /// <param name="headers">The headers of the response.</param>
        /// <param name="body">The body of the response.</param>
        public static HyperStatus HttpVersionNotSupported(HyperHeaderCollection headers, object? body, HyperSerializerDelegate serializer) => new HyperStatus()
        {
            Code = global::System.Net.HttpStatusCode.HttpVersionNotSupported,
            Headers = headers,
            Body = body,
            Serializer = serializer
        };
    }
}
