name: .NET Docs
on:
  release:
    types:
      - "published"
  push:
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "res/logo*"
      - "src/**"
      - "tools/**"
      - "Directory.Build.props"
      - "README.md"
      - "*.sln"
  workflow_dispatch:

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

permissions:
  contents: write

jobs:
  build:
    name: Build Docs
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
    - name: Install DocFX
      run: dotnet tool update -g docfx --prerelease
      continue-on-error: true
    - name: Build the project
      run: dotnet build
    - name: Build documentation
      run: docfx docs/docfx.json
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs/_site/
  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
